favicon: null
name: enderhxc
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1033278186805546
  brandStrength: 0.515205344883725
  rhythmicContrast: 0.8296404762659222
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.07061705435626209
typography_spectrum: 0.2003166263457388
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.292696
analytics:
  twitter: null
  google: null
  facebook: null
